import { runTests } from '@vscode/test-electron';
import { resolve, join } from 'node:path';
import { mkdir, writeFile, rm, readFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { build } from 'esbuild';
const extension = resolve(import.meta.dirname, '..');
const root = resolve(extension, '../..');
const workspace = join(root, 'build/vscode-smoke-workspace');
const unpacked = join(root, 'build/vscode-packaged-smoke');
await mkdir(workspace, { recursive: true });
await writeFile(join(workspace, 'doof.json'), JSON.stringify({ name: 'editor-smoke', build: { entry: 'main.do' } }));
await writeFile(join(workspace, 'main.do'), 'function main(): int {\n  name := "Doof"\n  name.substring(0, 1)\n  return 42\n  }\n');
await writeFile(join(workspace, 'workflow.test.do'), 'import { Assert } from "std/assert"\nexport function testSelected(): none {}\nexport function testSelectedOther(): none {\n  Assert.isFalse(true)\n}');
await mkdir(join(workspace, 'nested'), { recursive: true });
await writeFile(join(workspace, 'nested/doof.json'), JSON.stringify({ name: 'nested', build: { entry: 'main.do' } }));
await writeFile(join(workspace, 'nested/main.do'), 'function main(): int => 0');
await writeFile(join(workspace, 'nested/workflow.test.do'), 'export function testNested(): none {}');
await rm(unpacked, { recursive: true, force: true });
execFileSync('unzip', ['-q', join(extension, `doof-language-${JSON.parse(await readFile(join(extension, 'package.json'), 'utf8')).version}.vsix`), '-d', unpacked]);
await build({ entryPoints: [join(extension, 'src/extension-tests.ts')], outfile: join(extension, 'out/extension-tests.cjs'), bundle: true, platform: 'node', format: 'cjs', external: ['vscode'] });
await runTests({ vscodeExecutablePath: process.env.VSCODE_EXECUTABLE, extensionDevelopmentPath: join(unpacked, 'extension'), extensionTestsPath: join(extension, 'out/extension-tests.cjs'), cachePath: join(root, 'build/vscode-test'), launchArgs: [workspace, '--user-data-dir=' + join(root, 'build/vscode-test/profile'), '--extensions-dir=' + join(root, 'build/vscode-test/extensions'), '--disable-extensions', '--disable-workspace-trust', '--skip-welcome', '--skip-release-notes'], reuseMachineInstall: false });
